"""create_quotations_tables

Revision ID: 42d30a6e07ae
Revises: 2c6c7dd27543
Create Date: 2026-04-10 02:16:29.075337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42d30a6e07ae'
down_revision: Union[str, None] = '2c6c7dd27543'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
