"""create_invoices_tables

Revision ID: bd6f31e88431
Revises: 5b60e140e6d9
Create Date: 2026-04-10 02:29:13.846002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd6f31e88431'
down_revision: Union[str, None] = '5b60e140e6d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('number', sa.String(length=20), nullable=True),
    sa.Column('invoice_type', sa.String(length=5), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('client_document_type', sa.String(length=5), nullable=False),
    sa.Column('client_document', sa.String(length=20), nullable=False),
    sa.Column('client_email', sa.String(length=255), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('payment_method', sa.String(length=5), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('discount_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cufe', sa.String(length=96), nullable=True),
    sa.Column('dian_status', sa.String(length=20), nullable=False),
    sa.Column('dian_response', sa.Text(), nullable=True),
    sa.Column('xml_path', sa.String(length=512), nullable=True),
    sa.Column('pdf_path', sa.String(length=512), nullable=True),
    sa.Column('resolution_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('invoice_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_measure', sa.String(length=10), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('discount_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tax_code', sa.String(length=5), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_lines')
    op.drop_table('invoices')
    # ### end Alembic commands ###
