"""add_software_pin_and_wsdl_url

Revision ID: c894dd33686a
Revises: f954d30ca5d7
Create Date: 2026-04-10 01:28:48.885006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c894dd33686a'
down_revision: Union[str, None] = 'f954d30ca5d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_settings', sa.Column('software_pin', sa.String(length=10), nullable=True))
    op.add_column('company_settings', sa.Column('dian_wsdl_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_settings', 'dian_wsdl_url')
    op.drop_column('company_settings', 'software_pin')
    # ### end Alembic commands ###
