"""initial_tables

Revision ID: f954d30ca5d7
Revises: 
Create Date: 2026-04-10 00:17:11.532557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f954d30ca5d7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nit', sa.String(length=20), nullable=False),
    sa.Column('check_digit', sa.String(length=1), nullable=False),
    sa.Column('razon_social', sa.String(length=255), nullable=False),
    sa.Column('fiscal_regime', sa.Enum('simplificado', 'comun', name='fiscal_regime_enum'), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('cert_path', sa.String(length=512), nullable=True),
    sa.Column('cert_passphrase_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('dian_environment', sa.Enum('habilitacion', 'produccion', name='dian_environment_enum'), nullable=True),
    sa.Column('profile_execution_id', sa.String(length=100), nullable=True),
    sa.CheckConstraint('id = 1', name='single_row'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('numbering_resolutions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prefix', sa.String(length=10), nullable=False),
    sa.Column('from_number', sa.Integer(), nullable=False),
    sa.Column('to_number', sa.Integer(), nullable=False),
    sa.Column('current_number', sa.Integer(), nullable=True),
    sa.Column('technical_key', sa.String(length=255), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=False),
    sa.Column('resolution_number', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('numbering_resolutions')
    op.drop_table('company_settings')
    # ### end Alembic commands ###
